# This is the configuration file for label stage with VASP.
# The configuration contains 2 parts: executor context and workflow params.

executors:
  # This should correspond to the executor name in executor.yml
  hpc-cluster01:
    context:
      label:
        vasp:
          # The template used to generate submit script.
          script_template:
            # Specify the header of the submit script,
            # Should be configured according to your system.
            header: |
              #SBATCH -N 1
              #SBATCH --ntasks-per-node=16
              #SBATCH --job-name=vasp
              #SBATCH --partition=cpu

            # Specify the setup commands of the submit script,
            # Should be configured according to your system.
            setup: |
              set -e
              module load intel/17.5.239 mpi/intel/2017.5.239
              module load vasp/5.4.4
              set +e

          # Optional, specify the command to run deepmd-kit, default: vasp_std.
          vasp_cmd: vasp_std

          # Optional, specify the number of concurrent tasks, default: 0 (no limit)
          concurrency: 18

workflow:
  label:
    vasp:
      # Optional, limit the number of structures to label, default: 0 (no limit)
      limit: 10
      # The input template for VASP.
      # You can put the content of the input template here, as a dict, like:
      # input_template:
      #   SYSTEM: test
      #   ENCUT: 400
      # just as the INCAR file.
      # or you can put the INCAR file path here.
      # And put the POTCAR in the potcar_source, as a dict,
      # naming the key of the dict as the element name in the POTCAR.
      # Be sure to put all elements in the system you want to sampling in the potcar_source.
      #
      # Here we put the INCAR path in the configuration file.
      # For more information about INCAR, please refer to VASP documentation.

      input_template: "/path/to/incar/INCAR"
      potcar_source:
        C: "/path/to/pot/C/POTCAR"
        H: "/path/to/pot/H/POTCAR"
        O: "/path/to/pot/O/POTCAR"
