# This part defines the common parameters of the workflow.

workflow:
  # The general section defines the general parameters of the workflow.
  general:
    # Define the type_map and mass_map required by DeepMD-kit and structure format conversion.
    type_map: [H, O]
    mass_map: [1.008, 15.999]

    # Optional, limit the max iteration of workflow.
    # Default: 1
    max_iters: 10

    # Optional, whether to update the explore systems for each iteration.
    # Default: false
    update_explore_systems: false

  # The update section defines how to update the parameters of the workflow in each iteration.
  update:
    # The walkthrough updater is a table driven updater.
    # For each iteration, the updater will walk through the table and update the parameters of the workflow.
    # The updater will keep using the last row of the table until the max iteration is reached.
    walkthrough:
      # Optional, if it is set, the cursor will be moved to next row when the passing rate exceeds the threshold.
      # If it is not set, the cursor will be moved to next row for each iteration.
      passing_rate_threshold: 0.8

      # Optional, table of parameters to be updated.
      # Note that this table takes effect after the first iteration.
      # If you leave it empty, the workflow will keep using the parameters defined in the workflow section.
      table:
        # For example, the following setting will update the parameters of the workflow
        # and change the training epochs to 10000 when it takes effect.
        - train:
            deepmd:
              input_template:
                training:
                  numb_steps: 10000

        # And this setting will update the system files of the explore stage when it takes effect.
        - explore:
            lammps:
              system_files: [ explore-h2o_128 ]
