name: Build and Deploy Docs

on:
  repository_dispatch:
    types: [pypi-publish]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.compare-docs-and-notebooks.outputs.diff }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        token: ${{ secrets.GITLAB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make pandoc

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    #- name: Fetch latest docs from GitLab
    #  env:
    #    GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
    #    GITLAB_USER: ${{ secrets.GITLAB_USER }}
    #    GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
    #  run: |
    #    git clone https://${GITLAB_USER}:${GITLAB_TOKEN}@${GITLAB_REPO_URL}.git

    - name: Install dependencies
      run: |
        pip install ./ai2-kit
        pip install -r requirements.txt

    # API doc: update without PR
    - name: Sphinx APIDoc
      run: |
        sphinx-apidoc -f -o _api/ ai2-kit/ai2_kit/ --separate

    # Build the book
    - name: Build the book
      run: |
        sphinx-build -b html . _build

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      if: github.event_name != 'pull_request'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build

    # doc and notebook: needs to be reviewed
    - name: Compare doc and notebook
      id: compare-docs-and-notebooks
      run: |
        diff -r ai2-kit/doc doc || echo "Doc files are different" > diff.txt
        diff -r ai2-kit/notebook notebook || echo "Notebook files are different" >> diff.txt
        diff -r ai2-kit/example example || echo "Example files are different" >> diff.txt
        if [ -s diff.txt ]; then
        echo "::set-output name=diff::true"
        else
        echo "::set-output name=diff::false"
        fi
      continue-on-error: true

    - name: Commit changes
      if: steps.compare-docs-and-notebooks.outputs.diff == 'true'
      run: |
        cp -r ai2-kit/doc/* doc/
        cp -r ai2-kit/notebook/* notebook/
        cp -r ai2-kit/example/* example/

    - name: PR if doc or notebook changed
      if: steps.compare-docs-and-notebooks.outputs.diff == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update doc and notebook
        title: Update doc and notebook
        body: |
          This PR updates the doc and notebook to the latest version.
        branch: update-doc-and-notebook
        base: main