name: Check for version updates

on:
  schedule:
    # 每2小时运行一次
    - cron: '0 */2 * * *'
  workflow_dispatch:  # 允许手动触发


jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.check-version.outputs.version_changed }}
      new_version: ${{ steps.check-version.outputs.new_version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install requests
    - name: Check for version updates
      id: check-version
      run: python .github/scripts/check_version.py
    - name: Commit changes
      if: steps.check-version.outputs.version_changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add version.txt
        git commit -m "Update version to ${{ steps.check-version.outputs.new_version }}"
        git push